// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhqpB7zoFxoZTpfud8jn9FMBCUOtpvBN8',
    appId: '1:896546203503:web:a838877379c60f6496aa9a',
    messagingSenderId: '896546203503',
    projectId: 'chatproject-d70b4',
    authDomain: 'chatproject-d70b4.firebaseapp.com',
    storageBucket: 'chatproject-d70b4.appspot.com',
    measurementId: 'G-PC2XNHP7BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEoUbnSmZJegogJ5jhXS1KY1Tbf8K52G4',
    appId: '1:896546203503:android:b7f15ac1ae52cb9596aa9a',
    messagingSenderId: '896546203503',
    projectId: 'chatproject-d70b4',
    storageBucket: 'chatproject-d70b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2hmE4-5-XJoj_17LKGYQYs2pAbhpJxo',
    appId: '1:896546203503:ios:d8ff1b76e0e49c9f96aa9a',
    messagingSenderId: '896546203503',
    projectId: 'chatproject-d70b4',
    storageBucket: 'chatproject-d70b4.appspot.com',
    iosClientId: '896546203503-hf46i6p2o5kn140hta2alike1j7ofc7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL2hmE4-5-XJoj_17LKGYQYs2pAbhpJxo',
    appId: '1:896546203503:ios:67501aac3a07e98896aa9a',
    messagingSenderId: '896546203503',
    projectId: 'chatproject-d70b4',
    storageBucket: 'chatproject-d70b4.appspot.com',
    iosClientId: '896546203503-gfq4vl7loesjenode7l4lc1pnv0r6c5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashApp.RunnerTests',
  );
}
